# Site settings
title: KIM JISUN
description: NHNEnt. Intern
url: "https://wisesun93.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : 김지선
  bio      : NHNEnt. Intern
  email    : wisesun93@gmail.com
  instagram  : https://www.instagram.com/jsunny.kim/

#SEO settings
logo: /assets/img/image-blog.png/ # Site logo URL
instagram_username: jsunny.kim # instagram username

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
font_folder: "/assets/font"

sass:
    style: compressed