# Site settings
title: Minguss Tech Blog
description: Posting on Java, DevOps etc.. Technical post
url: "http://minguss821.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Minho Park
  bio      : DevOps Engineer passionate about new technologies. I am passionate about what I do and I try to learn more every day.
  email    : minopark8821@gmail.com

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL
twitter_username: minguss821 # Twitter username
facebook:
    app_id:  # App ID
    publisher:  # URL of the Facebook page
    admins:  # Facebook user ID that manages the page

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
